# -*- coding: utf-8 -*-
"""Employee attrition data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ovgr1fVhbesV3goxe2Qb4SKzTVei01he
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
data = pd.read_csv('/content/Attrition data.csv')

# Display the first few rows of the dataset
print(data.head())

# Data Cleaning
# Check for missing values
print(data.isnull().sum())

# Fill or drop missing values if necessary
data.fillna(method='ffill', inplace=True)  # Example: forward fill for missing values

# Convert 'Attrition' to a binary variable
data['Attrition'] = data['Attrition'].map({'Yes': 1, 'No': 0})

# EDA

# EDA: Attrition rate by department
plt.figure(figsize=(10, 6))
sns.countplot(data=data, x='Department', hue='Attrition')
plt.title('Attrition Rate by Department')
plt.xlabel('Department')
plt.ylabel('Number of Employees')
plt.legend(title='Attrition', labels=['No', 'Yes'])
plt.show()

# EDA: Attrition rate by Job Role
plt.figure(figsize=(12, 6))
sns.countplot(data=data, x='JobRole', hue='Attrition')
plt.title('Attrition Rate by Job Role')
plt.xlabel('Job Role')
plt.ylabel('Number of Employees')
plt.legend(title='Attrition', labels=['No', 'Yes'])
plt.xticks(rotation=45)
plt.show()

# Summary Statistics
summary_stats = data.describe()
print(summary_stats)

# Correlation Matrix
plt.figure(figsize=(12 , 10))
# Convert columns with 'object' dtype to numerical representations
for col in data.select_dtypes(include=['object']).columns:
    if col != 'Attrition': # Exclude the target variable if it's 'object' type
        data[col] = data[col].astype('category').cat.codes

correlation = data.corr()
sns.heatmap(correlation, annot=True, fmt=".2f", cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

#pair plot
sns.pairplot(data)
plt.show()

